### ISSUE TITLE
Doesn't work with react v17

### ISSUE THREAD

**Issue by devmakarov** [opentok/opentok-react#210]
Can you expand peerDependencies please? I can't install via 'npm i opentok-react '. Thank you!

**Comment by tjfroll** [comment]
With npm7, mismatched peer dependencies now cause a blocking error on install. This peer dependency is blocking us from upgrading to React 17.

**Comment by Oakyden** [comment]
You can use `npm install --legacy-peer-deps` if you have to for React 17.  More here https://stackoverflow.com/questions/66239691/what-does-npm-install-legacy-peer-deps-do-exactly-when-is-it-recommended-wh

**Comment by devwithzachary** [comment]
Good morning everyone, we are moving to fully support web components for OpenTok instead of just having a react package. The benefit of this is we can support a much wider range of JS frameworks from one repo. With just one code base to maintain we can be much more active in updates for the latest OpenTok versions.

The web components are currently in public beta as they don't have full feature parity with the react components just yet. But we will be building in the final features over the next couple of weeks with the hope to make this stable before the Christmas period.

We fully welcome any feedback and test on the new components so please check them out here https://github.com/opentok/web-components

We also have a react project example to show how to use these new components https://github.com/opentok/web-components/tree/main/examples/react
