### ISSUE TITLE
cycleVideo OT_HARDWARE_UNAVAILABLE

### ISSUE THREAD

**Issue by julien-meichelbeck** [opentok/opentok-react#55]
Sometimes, when calling `cycleVideo`, the OTPublisher unmounts and an error is thrown.

Example:
```jsx
<>
  <OTPublisher
    eventHandlers={{
      streamCreated: event => {
        this.publisher = event.target
      },
    }}
  />
  <button
    onClick={event => {
      event.preventDefault()
      if (this.publisher) this.publisher.cycleVideo()
    }}
  >
    Switch camera
  </button>
</>

```

Error :
```
OpenTok:Publisher:error onStreamAvailableError OT_HARDWARE_UNAVAILABLE: The selected voice or video devices are unavailable. Verify that the chosen devices are not in use by another application. (getUserMedia error: NotReadableError)
OpenTok:Publisher:warn Received connectivity event: "Failure" without "Attempt"
OpenTok:GlobalExceptionHandler:error OT.exception :: title: Unable to Publish (1500) msg: GetUserMedia
```

This issue can be seen on Android and iOS.

**Comment by msach22** [comment]
@julien-meichelbeck The `cycleVideo` method returns a promise so I recommend checking to see if the promise resolves or rejects. Please make sure you are running this on a device with multiple cameras.
I also recommend using the `ref` prop to get access to the publisher. You can the `getPublisher` method of the `OTPublisher` component to get the publisher object like so:
```
class MyComponent extends Component {
  constructor(props) {
    super(props);
    this.otPublisher = React.createRef();
  }
  cycleVideo = () => { 
   if (this.otPublisher) { 
    publisher = this.otPublisher.current.getPublisher();
    publisher.cycleVideo().then().catch() // implement custom logic here
   } 
  } 
  render() {
    return ( 
      <div>
        <OTPublisher ref={this.otPublisher} />;
        <button onClick={this.cycleVideo}> Cycle Video </button>
      </div>
    )
  }
}
```

**Comment by julien-meichelbeck** [comment]
Hello,

> returns a promise so I recommend checking to see if the promise resolves or rejects.

Yes, sure we can handle the promise, but it will not fix the issue.

> Please make sure you are running this on a device with multiple cameras.

Yes, this button is only displayed if there is more than one video device (following a `navigator.mediaDevices.enumerateDevices` call).

> I also recommend using the `ref` prop to get access to the publisher.

Thanks, this is looks better, but it doesn't actually fix anything, right ?

**Comment by msach22** [comment]
@julien-meichelbeck I believe the team had an offline chat with you about this and it was related to a specific device. I'm going to go ahead and close the issue, but please feel free to re-open if the issue still persists.

**Comment by satyanarayanaAmzur** [comment]
this issue was not closed brother msach22,still there are some glitches are pending like you know when we got and error from   publisher.cycleVideo(),the current ot-publisher was gots disturbed and  disappeared,if you some able to provide a solution if the promise returns catch block error then we are able use the current camera and providing some alert to user other device was being busy like wise ,if any dude implemented please do help me on this situation ,hope brother msach22  respond back with good solution for this,thanks in advance

**Comment by msach22** [comment]
@satyanarayanaAmzur If I understand correctly, you're saying that there's a glitch in the publisher even when there's an OT_HARDWARE_UNAVAILABLE error?

**Comment by satyanarayanaAmzur** [comment]
yes bro it was disappeared when we got an error,i mean the communication with current publisher was disturbed and publisher window was hidden from room

**Comment by BenRedmondBenham** [comment]
Sorry to revive this but I'm having the same issue with a oneplus 7 pro. 

![WhatsApp Image 2020-04-02 at 14 13 50](https://user-images.githubusercontent.com/4619062/78253942-15cc4080-74ed-11ea-84a3-1a2a72679fa6.jpeg)

When i call cycleVideo I get this error, but for some reason on this demo site https://opentokdemo.tokbox.com/ it works without any problems.

**Comment by kulttuuri** [comment]
Same error here on Galaxy A40 when trying to use cycleVideo.

**Comment by kulttuuri** [comment]
FYI; It seems like by calling `devices.stream.getTracks().forEach(track => track.stop());` before changing video device it prevented the error and is now working :)

**Comment by enricop89** [comment]
Hi guys, I tried to reproduce using `"@opentok/client": "^2.17.0"` and `"opentok-react": "0.10.0"` and is working perfectly.

I am using VDF 900 phone with Android 6.0.1 and `Chrome 80`

**Comment by kulttuuri** [comment]
I am using 2.17.0. I also tried with 2.15.0 to see if that is the problem. I believe that the issue only arises on some Android devices as the [linked PR commit](https://github.com/opentok/opentok-web-samples/pull/85) states.

**Comment by enricop89** [comment]
@kulttuuri would mind trying on https://opentokdemo.tokbox.com/ with your Galaxy A40? 👍

**Comment by goviewme** [comment]
Galaxy S20+ cycle video fails on the demo https://opentok.github.io/opentok-web-samples/Publish-Devices/  it also fails https://opentokdemo.tokbox.com/

**Comment by warren32** [comment]
Galaxy S20+ cycle video fails on the demo https://opentok.github.io/opentok-web-samples/Publish-Devices/ it also fails https://opentokdemo.tokbox.com/

**Comment by kulttuuri** [comment]
@enricop89 Weird - Now both demos worked on my Android, I am certain that they did not in the last week.

**Comment by weshamoh** [comment]
am almost giving up on this ..am trying to pass the session,so that subscriber can also view ,but i dont seem to get it am kinda of new am learning 

<script>
/* global OT */

(function closure() {
  const audioSelector = document.querySelector('#audio-source-select');
  const videoSelector = document.querySelector('#video-source-select');
  const publishBtn = document.querySelector('#publish-btn');
  const cycleVideoBtn = document.querySelector('#cycle-video-btn');
  let publisher;

var apiKey = "xxxx";
var sessionId = "xxxx";
var token = "xxxxx";

initializeSession();

function initializeSession() {
  var session = OT.initSession(apiKey, sessionId);

  // Subscribe to a newly created stream
  session.on('streamCreated', function(event) {
    var publisher = OT.initPublisher('publisher', {
   
      audioSource: audioSelector.value,
      videoSource: videoSelector.value
      
    }, handleError);
  });

 

  
  // Get the list of devices and populate the drop down lists
  function populateDeviceSources(selector, kind) {
    OT.getDevices((err, devices) => {
      if (err) {
        alert('getDevices error ' + err.message);
        return;
      }
      let index = 0;
      selector.innerHTML = devices.reduce((innerHTML, device) => {
        if (device.kind === kind) {
          index += 1;
          return `${innerHTML}<option value="${device.deviceId}">${device.label || device.kind + index}</option>`;
        }
        return innerHTML;
      }, '');
      publishBtn.disabled = false;
    });
  }
  publishBtn.disabled = true;
  // We request access to Microphones and Cameras so we can get the labels
  OT.getUserMedia().then((stream) => {
    populateDeviceSources(audioSelector, 'audioInput');
    populateDeviceSources(videoSelector, 'videoInput');
    // Stop the tracks so that we stop using this camera and microphone
    // If you don't do this then cycleVideo does not work on some Android devices
    stream.getTracks().forEach(track => track.stop());
  });

  // Start publishing when you click the publish button
  publishBtn.addEventListener('click', () => {
    // Disable the audio and video pickers and hide the publish button
    audioSelector.disabled = true;
    videoSelector.disabled = true;
    publishBtn.style.display = 'none';

    // Start publishing with the selected devices

  
  });

  // Allow you to switch to different cameras and microphones using
  // setAudioSource and cycleVideo
  function setupDeviceSwitching() {
    audioSelector.disabled = false;

    // When the audio selector changes we update the audio source
    audioSelector.addEventListener('change', () => {
      audioSelector.disabled = true;
      publisher.setAudioSource(event.target.value).then(() => {
        audioSelector.disabled = false;
      }).catch((err) => {
        alert(`setAudioSource failed: ${err.message}`);
        audioSelector.disabled = false;
      });
    });

    // When the cycleVideo button is clicked we call cycleVideo
    cycleVideoBtn.addEventListener('click', () => {
      cycleVideoBtn.disabled = true;
      publisher.cycleVideo().then(({ deviceId }) => {
        videoSelector.value = deviceId;
        cycleVideoBtn.disabled = false;
      }).catch((err) => {
        alert('cycleVideo error ' + err.message);
        cycleVideoBtn.disabled = false;
      });
    });
    cycleVideoBtn.style.display = 'inline-block';
  }

  function setupAudioLevelMeter() {
    const audioLevel = document.querySelector('#audio-meter');
    const meter = document.querySelector('#audio-meter meter');
    audioLevel.style.display = 'block';
    let movingAvg = null;
    publisher.on('audioLevelUpdated', (event) => {
      if (movingAvg === null || movingAvg <= event.audioLevel) {
        movingAvg = event.audioLevel;
      } else {
        movingAvg = 0.7 * movingAvg + 0.3 * event.audioLevel;
      }

      // 1.5 scaling to map the -30 - 0 dBm range to [0,1]
      var logLevel = (Math.log(movingAvg) / Math.LN10) / 1.5 + 1;
      logLevel = Math.min(Math.max(logLevel, 0), 1);
      meter.value = logLevel;
    });
  }





// Handling all of our errors here by alerting them
function handleError(error) {
  if (error) {
    alert(error.message);
  }
}

// (optional) add server code here

// Connect to the session
  session.connect(token, function(error) {
    // If the connection is successful, initialize a publisher and publish to the session
    if (error) {
      handleError(error);
    } else {
      session.publish(publisher, handleError);
    }
  });  



  
}

})();

</script>

**Comment by janosvajda** [comment]
Hi, there is the same issue if we use Tokbox in Electron.js app on Mac. We use the 2.17.7 version of Tokbox JS API.

**Comment by rochagbr** [comment]
Same issue here
